/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    int slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

#include <complex.h>

typedef _Complex double dcomplex;
#define real_dcomplex(z) creal(z)
#define imag_dcomplex(z) cimag(z)
#define setz_dcomplex(z,r,i)  *z = r + i*_Complex_I

typedef _Complex float fcomplex;
#define real_fcomplex(z) crealf(z)
#define imag_fcomplex(z) cimagf(z)
#define setz_fcomplex(z,r,i)  *z = r + i*_Complex_I

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)
mxWrapGetScalarZDef(mxWrapGetScalar_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapGetArrayZDef (mxWrapGetArray_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapCopyZDef     (mxWrapCopy_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapReturnZDef   (mxWrapReturn_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapGetScalarZDef(mxWrapGetScalar_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapGetArrayZDef (mxWrapGetArray_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapCopyZDef     (mxWrapCopy_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)
mxWrapReturnZDef   (mxWrapReturn_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)

#if defined(MWF77_CAPS)
#define MWF77_helm_c_p HELM_C_P
#define MWF77_helm_c_gn HELM_C_GN
#define MWF77_helm_d_p HELM_D_P
#elif defined(MWF77_UNDERSCORE1)
#define MWF77_helm_c_p helm_c_p_
#define MWF77_helm_c_gn helm_c_gn_
#define MWF77_helm_d_p helm_d_p_
#else /* f2c convention */
#define MWF77_helm_c_p helm_c_p__
#define MWF77_helm_c_gn helm_c_gn__
#define MWF77_helm_d_p helm_d_p__
#endif

#ifdef __cplusplus
extern "C" { /* Prevent C++ name mangling */
#endif

#ifndef MWF77_RETURN
#define MWF77_RETURN int
#endif

MWF77_RETURN MWF77_helm_c_p(int*, double*, int*, double*, dcomplex*, dcomplex*);
MWF77_RETURN MWF77_helm_c_gn(int*, double*, int*, double*, dcomplex*, dcomplex*);
MWF77_RETURN MWF77_helm_d_p(int*, double*, int*, double*, dcomplex*, dcomplex*);

#ifdef __cplusplus
} /* end extern C */
#endif

/* ---- helm_kernels.mw: 15 ----
 * helm_c_p(int[1] n, double[2, n] src0, int[1] m, double[2, m] targ0, dcomplex[1] zk, inout dcomplex[m, n] u);
 */
const char* stubids1_ = "helm_c_p(i int[x], i double[xx], i int[x], i double[xx], i dcomplex[x], io dcomplex[xx])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* n          */
    double*     in1_ =0; /* src0       */
    int*        in2_ =0; /* m          */
    double*     in3_ =0; /* targ0      */
    dcomplex*   in4_ =0; /* zk         */
    dcomplex*   in5_ =0; /* u          */
    int         dim6_;   /* 1          */
    int         dim7_;   /* 2          */
    int         dim8_;   /* n          */
    int         dim9_;   /* 1          */
    int         dim10_;   /* 2          */
    int         dim11_;   /* m          */
    int         dim12_;   /* 1          */
    int         dim13_;   /* m          */
    int         dim14_;   /* n          */

    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: n";        goto mw_err_label;
    }

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: src0";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: m";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim10_ ||
        mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: targ0";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: zk";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim13_ ||
        mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: u";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_dcomplex(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_dcomplex(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    MWF77_helm_c_p(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, dim14_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[0], in5_, dim13_*dim14_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in2_)  mxFree(in2_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- helm_kernels.mw: 33 ----
 * helm_c_gn(int[1] n, double[2, n] src0, int[1] m, double[4, m] targ0, dcomplex[1] zk, inout dcomplex[m, n] u);
 */
const char* stubids2_ = "helm_c_gn(i int[x], i double[xx], i int[x], i double[xx], i dcomplex[x], io dcomplex[xx])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* n          */
    double*     in1_ =0; /* src0       */
    int*        in2_ =0; /* m          */
    double*     in3_ =0; /* targ0      */
    dcomplex*   in4_ =0; /* zk         */
    dcomplex*   in5_ =0; /* u          */
    int         dim6_;   /* 1          */
    int         dim7_;   /* 2          */
    int         dim8_;   /* n          */
    int         dim9_;   /* 1          */
    int         dim10_;   /* 4          */
    int         dim11_;   /* m          */
    int         dim12_;   /* 1          */
    int         dim13_;   /* m          */
    int         dim14_;   /* n          */

    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: n";        goto mw_err_label;
    }

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: src0";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: m";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim10_ ||
        mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: targ0";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: zk";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim13_ ||
        mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: u";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_dcomplex(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_dcomplex(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    MWF77_helm_c_gn(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, dim14_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[0], in5_, dim13_*dim14_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in2_)  mxFree(in2_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- helm_kernels.mw: 50 ----
 * helm_d_p(int[1] n, double[4, n] src0, int[1] m, double[2, m] targ0, dcomplex[1] zk, inout dcomplex[m, n] u);
 */
const char* stubids3_ = "helm_d_p(i int[x], i double[xx], i int[x], i double[xx], i dcomplex[x], io dcomplex[xx])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* n          */
    double*     in1_ =0; /* src0       */
    int*        in2_ =0; /* m          */
    double*     in3_ =0; /* targ0      */
    dcomplex*   in4_ =0; /* zk         */
    dcomplex*   in5_ =0; /* u          */
    int         dim6_;   /* 1          */
    int         dim7_;   /* 4          */
    int         dim8_;   /* n          */
    int         dim9_;   /* 1          */
    int         dim10_;   /* 2          */
    int         dim11_;   /* m          */
    int         dim12_;   /* 1          */
    int         dim13_;   /* m          */
    int         dim14_;   /* n          */

    dim6_ = (int) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (int) mxWrapGetScalar(prhs[14], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: n";        goto mw_err_label;
    }

    if (mxGetM(prhs[1]) != dim7_ ||
        mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: src0";
        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: m";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim10_ ||
        mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: targ0";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: zk";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim13_ ||
        mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: u";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_dcomplex(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_dcomplex(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    MWF77_helm_d_p(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, dim14_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[0], in5_, dim13_*dim14_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in2_)  mxFree(in2_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(4 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 4 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to helm_kernels.mw:15\n", mexprofrecord_[1]);
        mexPrintf("%d calls to helm_kernels.mw:33\n", mexprofrecord_[2]);
        mexPrintf("%d calls to helm_kernels.mw:50\n", mexprofrecord_[3]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to helm_kernels.mw:15\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to helm_kernels.mw:33\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to helm_kernels.mw:50\n", mexprofrecord_[3]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

